package com.dozenx.web.core.log.bean;

import java.util.Date;

public class AppExceptionLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_exception_log.id
     *
     * @mbggenerated Sat Nov 07 23:18:44 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_exception_log.ClassName
     *
     * @mbggenerated Sat Nov 07 23:18:44 CST 2015
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_exception_log.sid
     *
     * @mbggenerated Sat Nov 07 23:18:44 CST 2015
     */
    private Integer sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_exception_log.lineNumber
     *
     * @mbggenerated Sat Nov 07 23:18:44 CST 2015
     */
    private Integer lineNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_exception_log.time
     *
     * @mbggenerated Sat Nov 07 23:18:44 CST 2015
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_exception_log.params
     *
     * @mbggenerated Sat Nov 07 23:18:44 CST 2015
     */
    private String params;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_exception_log.requesturl
     *
     * @mbggenerated Sat Nov 07 23:18:44 CST 2015
     */
    private String requesturl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_exception_log.msg
     *
     * @mbggenerated Sat Nov 07 23:18:44 CST 2015
     */
    private String msg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_exception_log.id
     *
     * @return the value of app_exception_log.id
     *
     * @mbggenerated Sat Nov 07 23:18:44 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_exception_log.id
     *
     * @param id the value for app_exception_log.id
     *
     * @mbggenerated Sat Nov 07 23:18:44 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_exception_log.ClassName
     *
     * @return the value of app_exception_log.ClassName
     *
     * @mbggenerated Sat Nov 07 23:18:44 CST 2015
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_exception_log.ClassName
     *
     * @param className the value for app_exception_log.ClassName
     *
     * @mbggenerated Sat Nov 07 23:18:44 CST 2015
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_exception_log.sid
     *
     * @return the value of app_exception_log.sid
     *
     * @mbggenerated Sat Nov 07 23:18:44 CST 2015
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_exception_log.sid
     *
     * @param sid the value for app_exception_log.sid
     *
     * @mbggenerated Sat Nov 07 23:18:44 CST 2015
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_exception_log.lineNumber
     *
     * @return the value of app_exception_log.lineNumber
     *
     * @mbggenerated Sat Nov 07 23:18:44 CST 2015
     */
    public Integer getLineNumber() {
        return lineNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_exception_log.lineNumber
     *
     * @param lineNumber the value for app_exception_log.lineNumber
     *
     * @mbggenerated Sat Nov 07 23:18:44 CST 2015
     */
    public void setLineNumber(Integer lineNumber) {
        this.lineNumber = lineNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_exception_log.time
     *
     * @return the value of app_exception_log.time
     *
     * @mbggenerated Sat Nov 07 23:18:44 CST 2015
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_exception_log.time
     *
     * @param time the value for app_exception_log.time
     *
     * @mbggenerated Sat Nov 07 23:18:44 CST 2015
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_exception_log.params
     *
     * @return the value of app_exception_log.params
     *
     * @mbggenerated Sat Nov 07 23:18:44 CST 2015
     */
    public String getParams() {
        return params;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_exception_log.params
     *
     * @param params the value for app_exception_log.params
     *
     * @mbggenerated Sat Nov 07 23:18:44 CST 2015
     */
    public void setParams(String params) {
        this.params = params == null ? null : params.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_exception_log.requesturl
     *
     * @return the value of app_exception_log.requesturl
     *
     * @mbggenerated Sat Nov 07 23:18:44 CST 2015
     */
    public String getRequesturl() {
        return requesturl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_exception_log.requesturl
     *
     * @param requesturl the value for app_exception_log.requesturl
     *
     * @mbggenerated Sat Nov 07 23:18:44 CST 2015
     */
    public void setRequesturl(String requesturl) {
        this.requesturl = requesturl == null ? null : requesturl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_exception_log.msg
     *
     * @return the value of app_exception_log.msg
     *
     * @mbggenerated Sat Nov 07 23:18:44 CST 2015
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_exception_log.msg
     *
     * @param msg the value for app_exception_log.msg
     *
     * @mbggenerated Sat Nov 07 23:18:44 CST 2015
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }
}