package com.dozenx.web.core.log.bean;

import com.dozenx.web.core.page.Page;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

;


public class FwLogExample {
    public Page getPage() {
		return page;
	}

	public void setPage(Page page) {
		this.page = page;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_fwlog_history_2015
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    protected String orderByClause;
    
    protected Page page;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_fwlog_history_2015
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_fwlog_history_2015
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fwlog_history_2015
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    public FwLogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fwlog_history_2015
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fwlog_history_2015
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fwlog_history_2015
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fwlog_history_2015
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fwlog_history_2015
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fwlog_history_2015
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fwlog_history_2015
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fwlog_history_2015
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fwlog_history_2015
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fwlog_history_2015
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_fwlog_history_2015
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andStartDateIsNull() {
            addCriterion("startDate is null");
            return (Criteria) this;
        }

        public Criteria andStartDateIsNotNull() {
            addCriterion("startDate is not null");
            return (Criteria) this;
        }

        public Criteria andStartDateEqualTo(Date value) {
            addCriterion("startDate =", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotEqualTo(Date value) {
            addCriterion("startDate <>", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateGreaterThan(Date value) {
            addCriterion("startDate >", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateGreaterThanOrEqualTo(Date value) {
            addCriterion("startDate >=", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLessThan(Date value) {
            addCriterion("startDate <", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLessThanOrEqualTo(Date value) {
            addCriterion("startDate <=", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateIn(List<Date> values) {
            addCriterion("startDate in", values, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotIn(List<Date> values) {
            addCriterion("startDate not in", values, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateBetween(Date value1, Date value2) {
            addCriterion("startDate between", value1, value2, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotBetween(Date value1, Date value2) {
            addCriterion("startDate not between", value1, value2, "startDate");
            return (Criteria) this;
        }

        public Criteria andStrDateIsNull() {
            addCriterion("strDate is null");
            return (Criteria) this;
        }

        public Criteria andStrDateIsNotNull() {
            addCriterion("strDate is not null");
            return (Criteria) this;
        }

        public Criteria andStrDateEqualTo(String value) {
            addCriterion("strDate =", value, "strDate");
            return (Criteria) this;
        }

        public Criteria andStrDateNotEqualTo(String value) {
            addCriterion("strDate <>", value, "strDate");
            return (Criteria) this;
        }

        public Criteria andStrDateGreaterThan(String value) {
            addCriterion("strDate >", value, "strDate");
            return (Criteria) this;
        }

        public Criteria andStrDateGreaterThanOrEqualTo(String value) {
            addCriterion("strDate >=", value, "strDate");
            return (Criteria) this;
        }

        public Criteria andStrDateLessThan(String value) {
            addCriterion("strDate <", value, "strDate");
            return (Criteria) this;
        }

        public Criteria andStrDateLessThanOrEqualTo(String value) {
            addCriterion("strDate <=", value, "strDate");
            return (Criteria) this;
        }

        public Criteria andStrDateLike(String value) {
            addCriterion("strDate like", value, "strDate");
            return (Criteria) this;
        }

        public Criteria andStrDateNotLike(String value) {
            addCriterion("strDate not like", value, "strDate");
            return (Criteria) this;
        }

        public Criteria andStrDateIn(List<String> values) {
            addCriterion("strDate in", values, "strDate");
            return (Criteria) this;
        }

        public Criteria andStrDateNotIn(List<String> values) {
            addCriterion("strDate not in", values, "strDate");
            return (Criteria) this;
        }

        public Criteria andStrDateBetween(String value1, String value2) {
            addCriterion("strDate between", value1, value2, "strDate");
            return (Criteria) this;
        }

        public Criteria andStrDateNotBetween(String value1, String value2) {
            addCriterion("strDate not between", value1, value2, "strDate");
            return (Criteria) this;
        }

        public Criteria andTomcatIsNull() {
            addCriterion("tomcat is null");
            return (Criteria) this;
        }

        public Criteria andTomcatIsNotNull() {
            addCriterion("tomcat is not null");
            return (Criteria) this;
        }

        public Criteria andTomcatEqualTo(String value) {
            addCriterion("tomcat =", value, "tomcat");
            return (Criteria) this;
        }

        public Criteria andTomcatNotEqualTo(String value) {
            addCriterion("tomcat <>", value, "tomcat");
            return (Criteria) this;
        }

        public Criteria andTomcatGreaterThan(String value) {
            addCriterion("tomcat >", value, "tomcat");
            return (Criteria) this;
        }

        public Criteria andTomcatGreaterThanOrEqualTo(String value) {
            addCriterion("tomcat >=", value, "tomcat");
            return (Criteria) this;
        }

        public Criteria andTomcatLessThan(String value) {
            addCriterion("tomcat <", value, "tomcat");
            return (Criteria) this;
        }

        public Criteria andTomcatLessThanOrEqualTo(String value) {
            addCriterion("tomcat <=", value, "tomcat");
            return (Criteria) this;
        }

        public Criteria andTomcatLike(String value) {
            addCriterion("tomcat like", value, "tomcat");
            return (Criteria) this;
        }

        public Criteria andTomcatNotLike(String value) {
            addCriterion("tomcat not like", value, "tomcat");
            return (Criteria) this;
        }

        public Criteria andTomcatIn(List<String> values) {
            addCriterion("tomcat in", values, "tomcat");
            return (Criteria) this;
        }

        public Criteria andTomcatNotIn(List<String> values) {
            addCriterion("tomcat not in", values, "tomcat");
            return (Criteria) this;
        }

        public Criteria andTomcatBetween(String value1, String value2) {
            addCriterion("tomcat between", value1, value2, "tomcat");
            return (Criteria) this;
        }

        public Criteria andTomcatNotBetween(String value1, String value2) {
            addCriterion("tomcat not between", value1, value2, "tomcat");
            return (Criteria) this;
        }

        public Criteria andUserCodeIsNull() {
            addCriterion("userCode is null");
            return (Criteria) this;
        }

        public Criteria andUserCodeIsNotNull() {
            addCriterion("userCode is not null");
            return (Criteria) this;
        }

        public Criteria andUserCodeEqualTo(String value) {
            addCriterion("userCode =", value, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeNotEqualTo(String value) {
            addCriterion("userCode <>", value, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeGreaterThan(String value) {
            addCriterion("userCode >", value, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeGreaterThanOrEqualTo(String value) {
            addCriterion("userCode >=", value, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeLessThan(String value) {
            addCriterion("userCode <", value, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeLessThanOrEqualTo(String value) {
            addCriterion("userCode <=", value, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeLike(String value) {
            addCriterion("userCode like", value, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeNotLike(String value) {
            addCriterion("userCode not like", value, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeIn(List<String> values) {
            addCriterion("userCode in", values, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeNotIn(List<String> values) {
            addCriterion("userCode not in", values, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeBetween(String value1, String value2) {
            addCriterion("userCode between", value1, value2, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeNotBetween(String value1, String value2) {
            addCriterion("userCode not between", value1, value2, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNull() {
            addCriterion("userName is null");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("userName is not null");
            return (Criteria) this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("userName =", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("userName <>", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("userName >", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("userName >=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("userName <", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("userName <=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("userName like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("userName not like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameIn(List<String> values) {
            addCriterion("userName in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotIn(List<String> values) {
            addCriterion("userName not in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("userName between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("userName not between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andSessionIdIsNull() {
            addCriterion("sessionId is null");
            return (Criteria) this;
        }

        public Criteria andSessionIdIsNotNull() {
            addCriterion("sessionId is not null");
            return (Criteria) this;
        }

        public Criteria andSessionIdEqualTo(String value) {
            addCriterion("sessionId =", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdNotEqualTo(String value) {
            addCriterion("sessionId <>", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdGreaterThan(String value) {
            addCriterion("sessionId >", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdGreaterThanOrEqualTo(String value) {
            addCriterion("sessionId >=", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdLessThan(String value) {
            addCriterion("sessionId <", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdLessThanOrEqualTo(String value) {
            addCriterion("sessionId <=", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdLike(String value) {
            addCriterion("sessionId like", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdNotLike(String value) {
            addCriterion("sessionId not like", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdIn(List<String> values) {
            addCriterion("sessionId in", values, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdNotIn(List<String> values) {
            addCriterion("sessionId not in", values, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdBetween(String value1, String value2) {
            addCriterion("sessionId between", value1, value2, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdNotBetween(String value1, String value2) {
            addCriterion("sessionId not between", value1, value2, "sessionId");
            return (Criteria) this;
        }

        public Criteria andIpIsNull() {
            addCriterion("ip is null");
            return (Criteria) this;
        }

        public Criteria andIpIsNotNull() {
            addCriterion("ip is not null");
            return (Criteria) this;
        }

        public Criteria andIpEqualTo(String value) {
            addCriterion("ip =", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotEqualTo(String value) {
            addCriterion("ip <>", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpGreaterThan(String value) {
            addCriterion("ip >", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpGreaterThanOrEqualTo(String value) {
            addCriterion("ip >=", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLessThan(String value) {
            addCriterion("ip <", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLessThanOrEqualTo(String value) {
            addCriterion("ip <=", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLike(String value) {
            addCriterion("ip like", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotLike(String value) {
            addCriterion("ip not like", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpIn(List<String> values) {
            addCriterion("ip in", values, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotIn(List<String> values) {
            addCriterion("ip not in", values, "ip");
            return (Criteria) this;
        }

        public Criteria andIpBetween(String value1, String value2) {
            addCriterion("ip between", value1, value2, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotBetween(String value1, String value2) {
            addCriterion("ip not between", value1, value2, "ip");
            return (Criteria) this;
        }

        public Criteria andFwUrlIsNull() {
            addCriterion("fwUrl is null");
            return (Criteria) this;
        }

        public Criteria andFwUrlIsNotNull() {
            addCriterion("fwUrl is not null");
            return (Criteria) this;
        }

        public Criteria andFwUrlEqualTo(String value) {
            addCriterion("fwUrl =", value, "fwUrl");
            return (Criteria) this;
        }

        public Criteria andFwUrlNotEqualTo(String value) {
            addCriterion("fwUrl <>", value, "fwUrl");
            return (Criteria) this;
        }

        public Criteria andFwUrlGreaterThan(String value) {
            addCriterion("fwUrl >", value, "fwUrl");
            return (Criteria) this;
        }

        public Criteria andFwUrlGreaterThanOrEqualTo(String value) {
            addCriterion("fwUrl >=", value, "fwUrl");
            return (Criteria) this;
        }

        public Criteria andFwUrlLessThan(String value) {
            addCriterion("fwUrl <", value, "fwUrl");
            return (Criteria) this;
        }

        public Criteria andFwUrlLessThanOrEqualTo(String value) {
            addCriterion("fwUrl <=", value, "fwUrl");
            return (Criteria) this;
        }

        public Criteria andFwUrlLike(String value) {
            addCriterion("fwUrl like", value, "fwUrl");
            return (Criteria) this;
        }

        public Criteria andFwUrlNotLike(String value) {
            addCriterion("fwUrl not like", value, "fwUrl");
            return (Criteria) this;
        }

        public Criteria andFwUrlIn(List<String> values) {
            addCriterion("fwUrl in", values, "fwUrl");
            return (Criteria) this;
        }

        public Criteria andFwUrlNotIn(List<String> values) {
            addCriterion("fwUrl not in", values, "fwUrl");
            return (Criteria) this;
        }

        public Criteria andFwUrlBetween(String value1, String value2) {
            addCriterion("fwUrl between", value1, value2, "fwUrl");
            return (Criteria) this;
        }

        public Criteria andFwUrlNotBetween(String value1, String value2) {
            addCriterion("fwUrl not between", value1, value2, "fwUrl");
            return (Criteria) this;
        }

        public Criteria andMenuNameIsNull() {
            addCriterion("menuName is null");
            return (Criteria) this;
        }

        public Criteria andMenuNameIsNotNull() {
            addCriterion("menuName is not null");
            return (Criteria) this;
        }

        public Criteria andMenuNameEqualTo(String value) {
            addCriterion("menuName =", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameNotEqualTo(String value) {
            addCriterion("menuName <>", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameGreaterThan(String value) {
            addCriterion("menuName >", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameGreaterThanOrEqualTo(String value) {
            addCriterion("menuName >=", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameLessThan(String value) {
            addCriterion("menuName <", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameLessThanOrEqualTo(String value) {
            addCriterion("menuName <=", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameLike(String value) {
            addCriterion("menuName like", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameNotLike(String value) {
            addCriterion("menuName not like", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameIn(List<String> values) {
            addCriterion("menuName in", values, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameNotIn(List<String> values) {
            addCriterion("menuName not in", values, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameBetween(String value1, String value2) {
            addCriterion("menuName between", value1, value2, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameNotBetween(String value1, String value2) {
            addCriterion("menuName not between", value1, value2, "menuName");
            return (Criteria) this;
        }

        public Criteria andIsqxIsNull() {
            addCriterion("isqx is null");
            return (Criteria) this;
        }

        public Criteria andIsqxIsNotNull() {
            addCriterion("isqx is not null");
            return (Criteria) this;
        }

        public Criteria andIsqxEqualTo(String value) {
            addCriterion("isqx =", value, "isqx");
            return (Criteria) this;
        }

        public Criteria andIsqxNotEqualTo(String value) {
            addCriterion("isqx <>", value, "isqx");
            return (Criteria) this;
        }

        public Criteria andIsqxGreaterThan(String value) {
            addCriterion("isqx >", value, "isqx");
            return (Criteria) this;
        }

        public Criteria andIsqxGreaterThanOrEqualTo(String value) {
            addCriterion("isqx >=", value, "isqx");
            return (Criteria) this;
        }

        public Criteria andIsqxLessThan(String value) {
            addCriterion("isqx <", value, "isqx");
            return (Criteria) this;
        }

        public Criteria andIsqxLessThanOrEqualTo(String value) {
            addCriterion("isqx <=", value, "isqx");
            return (Criteria) this;
        }

        public Criteria andIsqxLike(String value) {
            addCriterion("isqx like", value, "isqx");
            return (Criteria) this;
        }

        public Criteria andIsqxNotLike(String value) {
            addCriterion("isqx not like", value, "isqx");
            return (Criteria) this;
        }

        public Criteria andIsqxIn(List<String> values) {
            addCriterion("isqx in", values, "isqx");
            return (Criteria) this;
        }

        public Criteria andIsqxNotIn(List<String> values) {
            addCriterion("isqx not in", values, "isqx");
            return (Criteria) this;
        }

        public Criteria andIsqxBetween(String value1, String value2) {
            addCriterion("isqx between", value1, value2, "isqx");
            return (Criteria) this;
        }

        public Criteria andIsqxNotBetween(String value1, String value2) {
            addCriterion("isqx not between", value1, value2, "isqx");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_fwlog_history_2015
     *
     * @mbggenerated do_not_delete_during_merge Tue Nov 10 23:49:42 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_fwlog_history_2015
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}