package com.dozenx.web.core.log.bean;

import java.util.Date;

public class FwLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fwlog_history_2015.id
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fwlog_history_2015.startDate
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fwlog_history_2015.strDate
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    private String strDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fwlog_history_2015.tomcat
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    private String tomcat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fwlog_history_2015.userCode
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    private String userCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fwlog_history_2015.userName
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fwlog_history_2015.sessionId
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    private String sessionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fwlog_history_2015.ip
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fwlog_history_2015.fwUrl
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    private String fwUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fwlog_history_2015.menuName
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    private String menuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fwlog_history_2015.isqx
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    private String isqx;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fwlog_history_2015.id
     *
     * @return the value of t_fwlog_history_2015.id
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fwlog_history_2015.id
     *
     * @param id the value for t_fwlog_history_2015.id
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fwlog_history_2015.startDate
     *
     * @return the value of t_fwlog_history_2015.startDate
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fwlog_history_2015.startDate
     *
     * @param startDate the value for t_fwlog_history_2015.startDate
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fwlog_history_2015.strDate
     *
     * @return the value of t_fwlog_history_2015.strDate
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    public String getStrDate() {
        return strDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fwlog_history_2015.strDate
     *
     * @param strDate the value for t_fwlog_history_2015.strDate
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    public void setStrDate(String strDate) {
        this.strDate = strDate == null ? null : strDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fwlog_history_2015.tomcat
     *
     * @return the value of t_fwlog_history_2015.tomcat
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    public String getTomcat() {
        return tomcat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fwlog_history_2015.tomcat
     *
     * @param tomcat the value for t_fwlog_history_2015.tomcat
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    public void setTomcat(String tomcat) {
        this.tomcat = tomcat == null ? null : tomcat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fwlog_history_2015.userCode
     *
     * @return the value of t_fwlog_history_2015.userCode
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fwlog_history_2015.userCode
     *
     * @param userCode the value for t_fwlog_history_2015.userCode
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fwlog_history_2015.userName
     *
     * @return the value of t_fwlog_history_2015.userName
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fwlog_history_2015.userName
     *
     * @param userName the value for t_fwlog_history_2015.userName
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fwlog_history_2015.sessionId
     *
     * @return the value of t_fwlog_history_2015.sessionId
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    public String getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fwlog_history_2015.sessionId
     *
     * @param sessionId the value for t_fwlog_history_2015.sessionId
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId == null ? null : sessionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fwlog_history_2015.ip
     *
     * @return the value of t_fwlog_history_2015.ip
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fwlog_history_2015.ip
     *
     * @param ip the value for t_fwlog_history_2015.ip
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fwlog_history_2015.fwUrl
     *
     * @return the value of t_fwlog_history_2015.fwUrl
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    public String getFwUrl() {
        return fwUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fwlog_history_2015.fwUrl
     *
     * @param fwUrl the value for t_fwlog_history_2015.fwUrl
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    public void setFwUrl(String fwUrl) {
        this.fwUrl = fwUrl == null ? null : fwUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fwlog_history_2015.menuName
     *
     * @return the value of t_fwlog_history_2015.menuName
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fwlog_history_2015.menuName
     *
     * @param menuName the value for t_fwlog_history_2015.menuName
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fwlog_history_2015.isqx
     *
     * @return the value of t_fwlog_history_2015.isqx
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    public String getIsqx() {
        return isqx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fwlog_history_2015.isqx
     *
     * @param isqx the value for t_fwlog_history_2015.isqx
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    public void setIsqx(String isqx) {
        this.isqx = isqx == null ? null : isqx.trim();
    }
}