package com.dozenx.web.core.log.dao;

import com.dozenx.web.core.log.bean.AppExceptionLog;
import com.dozenx.web.core.log.bean.AppExceptionLogExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;


@Component("appExceptionLogMapper") 
public interface AppExceptionLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_exception_log
     *
     * @mbggenerated Sat Nov 07 23:18:44 CST 2015
     */
    int countByExample(AppExceptionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_exception_log
     *
     * @mbggenerated Sat Nov 07 23:18:44 CST 2015
     */
    int deleteByExample(AppExceptionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_exception_log
     *
     * @mbggenerated Sat Nov 07 23:18:44 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_exception_log
     *
     * @mbggenerated Sat Nov 07 23:18:44 CST 2015
     */
    int insert(AppExceptionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_exception_log
     *
     * @mbggenerated Sat Nov 07 23:18:44 CST 2015
     */
    int insertSelective(AppExceptionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_exception_log
     *
     * @mbggenerated Sat Nov 07 23:18:44 CST 2015
     */
    List<AppExceptionLog> selectByExampleWithBLOBs(AppExceptionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_exception_log
     *
     * @mbggenerated Sat Nov 07 23:18:44 CST 2015
     */
    List<AppExceptionLog> selectByExample(AppExceptionLogExample example);
    
    
    /**
     * 说明:分页查询
     * @param example
     * @return
     * @return List<AppExceptionLog>
     * @author dozen.zhang
     * @date 2015年11月11日上午9:55:13
     */
    List<AppExceptionLog> selectByExample4Page(AppExceptionLogExample example);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_exception_log
     *
     * @mbggenerated Sat Nov 07 23:18:44 CST 2015
     */
    AppExceptionLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_exception_log
     *
     * @mbggenerated Sat Nov 07 23:18:44 CST 2015
     */
    int updateByExampleSelective(@Param("record") AppExceptionLog record, @Param("example") AppExceptionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_exception_log
     *
     * @mbggenerated Sat Nov 07 23:18:44 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") AppExceptionLog record, @Param("example") AppExceptionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_exception_log
     *
     * @mbggenerated Sat Nov 07 23:18:44 CST 2015
     */
    int updateByExample(@Param("record") AppExceptionLog record, @Param("example") AppExceptionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_exception_log
     *
     * @mbggenerated Sat Nov 07 23:18:44 CST 2015
     */
    int updateByPrimaryKeySelective(AppExceptionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_exception_log
     *
     * @mbggenerated Sat Nov 07 23:18:44 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(AppExceptionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_exception_log
     *
     * @mbggenerated Sat Nov 07 23:18:44 CST 2015
     */
    int updateByPrimaryKey(AppExceptionLog record);
}