package com.dozenx.web.core.log.dao;

import com.dozenx.web.core.log.bean.FwLog;
import com.dozenx.web.core.log.bean.FwLogExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;
@Component("fwLogMapper") 
public interface FwLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fwlog_history_2015
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    int countByExample(FwLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fwlog_history_2015
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    int deleteByExample(FwLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fwlog_history_2015
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fwlog_history_2015
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    int insert(FwLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fwlog_history_2015
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    int insertSelective(FwLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fwlog_history_2015
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    List<FwLog> selectByExample(FwLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fwlog_history_2015
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    FwLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fwlog_history_2015
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    int updateByExampleSelective(@Param("record") FwLog record, @Param("example") FwLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fwlog_history_2015
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    int updateByExample(@Param("record") FwLog record, @Param("example") FwLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fwlog_history_2015
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    int updateByPrimaryKeySelective(FwLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fwlog_history_2015
     *
     * @mbggenerated Tue Nov 10 23:49:42 CST 2015
     */
    int updateByPrimaryKey(FwLog record);
    
    
    /**
     * 说明:访问日志分页
     * @param map
     * @return
     * @return List<HashMap>
     * @author dozen.zhang
     * @date 2015年11月11日上午12:16:48
     */
//    List<HashMap> selectLogList4Page(HashMap map);

	/**
	 * 说明: 分页查询
	 * @param example
	 * @return
	 * @return List<FwLog>
	 * @author dozen.zhang
	 * @date 2015年11月11日上午9:50:21
	 */
	List<FwLog> selectByExample4Page(FwLogExample example);


}